### ISSUE TITLE
Can a Raspberry PI run Java?

### ISSUE THREAD

**Issue by UserXXX** [UserXXX/vCom#1]
Can a Raspberry PI run normal Java applications or is it necessary to use a subset of the Java API? Is it possible to use the Java Native Interface (JNI) on a Raspberry PI? Do external C libraries for JNI need a specific compilation environment / compiler?

**Comment by Kaische** [comment]
A Raspberry Pi can run Java SE 8. JavaFX is not supported (http://www.oracle.com/technetwork/java/javase/certconfig-2095354.html).
JNI can be used.
